USE [master]
GO

/****** Object:  Database [prestamodb]    Script Date: 11-Jun-16 10:42:24 AM ******/
CREATE DATABASE [prestamodb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'prestamodb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\prestamodb.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'prestamodb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\prestamodb_log.ldf' , SIZE = 816KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [prestamodb] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [prestamodb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [prestamodb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [prestamodb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [prestamodb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [prestamodb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [prestamodb] SET ARITHABORT OFF 
GO

ALTER DATABASE [prestamodb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [prestamodb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [prestamodb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [prestamodb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [prestamodb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [prestamodb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [prestamodb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [prestamodb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [prestamodb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [prestamodb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [prestamodb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [prestamodb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [prestamodb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [prestamodb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [prestamodb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [prestamodb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [prestamodb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [prestamodb] SET RECOVERY FULL 
GO

ALTER DATABASE [prestamodb] SET  MULTI_USER 
GO

ALTER DATABASE [prestamodb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [prestamodb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [prestamodb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [prestamodb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [prestamodb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [prestamodb] SET  READ_WRITE 
GO

