//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisPrestamo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Prestamos")]
    public partial class Prestamo
    {
        public int Id { get; set; }
        public int ClienteId { get; set; }
        public int Importe { get; set; }
        public int Tasa { get; set; }
        public DateTime Plazo { get; set; }
        public int tipo_prestamoId { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual tipo_prestamo tipo_prestamo { get; set; }
    }
}
