//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisPrestamo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        public int id { get; set; }
        public int id_cliente { get; set; }
        public Nullable<int> Importe { get; set; }
        public Nullable<int> Tasa { get; set; }
        public Nullable<System.DateTime> Plazo { get; set; }
        public Nullable<int> tipo_prestamo { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual tipo_prestamo tipo_prestamo1 { get; set; }
    }
}
