// <auto-generated />
namespace SisPrestamo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class creatingTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(creatingTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201608060252189_creatingTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
