// <auto-generated />
namespace SisPrestamo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addingchanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingchanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201608071310583_addingchanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
