// <auto-generated />
namespace SisPrestamo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updating : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updating));
        
        string IMigrationMetadata.Id
        {
            get { return "201608060259006_updating"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
